import type {
  GitHubConnection,
  Label,
  Milestone,
  Project,
  ProjectStatus,
  Session,
  SyncEvent,
  Task,
  WorkspaceData,
} from "@/lib/types"

export const demoProject: Project = {
  id: "project-northstar",
  name: "Northstar customer portal",
  key: "NORTH",
  description:
    "A calm, transparent delivery space for the Northstar team and their customers.",
  startDate: "2026-08-17",
  targetDate: "2026-10-16",
  status: "active",
  version: 7,
}

export const demoProjects: Project[] = [
  demoProject,
  {
    id: "project-atlas",
    name: "Atlas mobile refresh",
    key: "ATLAS",
    description: "A focused product refresh for the mobile experience.",
    startDate: "2026-09-07",
    targetDate: "2026-11-06",
    status: "active",
    version: 2,
  },
  {
    id: "project-lumen",
    name: "Lumen launch system",
    key: "LUMEN",
    description: "Launch planning and content operations for the fall release.",
    startDate: "2026-07-20",
    targetDate: "2026-09-25",
    status: "active",
    version: 11,
  },
]

export const demoStatuses: ProjectStatus[] = [
  {
    id: "status-backlog",
    name: "Backlog",
    category: "backlog",
    position: 0,
    color: "#94a3b8",
  },
  {
    id: "status-todo",
    name: "Todo",
    category: "todo",
    position: 1,
    color: "#60a5fa",
  },
  {
    id: "status-progress",
    name: "In progress",
    category: "in_progress",
    position: 2,
    color: "#8b5cf6",
  },
  {
    id: "status-blocked",
    name: "Blocked",
    category: "blocked",
    position: 3,
    color: "#f59e0b",
  },
  {
    id: "status-done",
    name: "Done",
    category: "done",
    position: 4,
    color: "#22c55e",
  },
]

const demoLabels: Label[] = [
  { id: "label-design", name: "Design", color: "#f59e0b" },
  { id: "label-dev", name: "Development", color: "#6366f1" },
  { id: "label-customer", name: "Customer", color: "#14b8a6" },
  { id: "label-review", name: "Review", color: "#ec4899" },
]

export const demoTasks: Task[] = [
  {
    id: "task-discovery",
    projectId: demoProject.id,
    statusId: "status-done",
    statusName: "Done",
    statusCategory: "done",
    title: "Discovery & success criteria",
    description:
      "Align on the customer-facing project story and launch signals.",
    priority: "high",
    startDate: "2026-08-17",
    dueDate: "2026-08-21",
    estimateMinutes: 960,
    assigneeName: "Ava Morgan",
    visibility: "customer",
    position: 0,
    version: 3,
    labels: [demoLabels[2]],
  },
  {
    id: "task-foundation",
    projectId: demoProject.id,
    statusId: "status-progress",
    statusName: "In progress",
    statusCategory: "in_progress",
    title: "Project foundation",
    description:
      "Set up the core information architecture and workspace shell.",
    priority: "urgent",
    startDate: "2026-08-24",
    dueDate: "2026-09-04",
    estimateMinutes: 1440,
    assigneeName: "Milo Chen",
    visibility: "customer",
    position: 1,
    version: 4,
    labels: [demoLabels[1]],
  },
  {
    id: "task-portal",
    projectId: demoProject.id,
    parentId: "task-foundation",
    statusId: "status-progress",
    statusName: "In progress",
    statusCategory: "in_progress",
    title: "Customer project portal",
    description:
      "Read-only status view with milestones and approved deliverables.",
    priority: "high",
    startDate: "2026-09-01",
    dueDate: "2026-09-18",
    estimateMinutes: 1920,
    assigneeName: "Milo Chen",
    visibility: "customer",
    position: 0,
    version: 2,
    labels: [demoLabels[2], demoLabels[1]],
  },
  {
    id: "task-statuses",
    projectId: demoProject.id,
    parentId: "task-foundation",
    statusId: "status-todo",
    statusName: "Todo",
    statusCategory: "todo",
    title: "Workflow and status mapping",
    description:
      "Define the project-specific statuses and GitHub open/closed mapping.",
    priority: "medium",
    startDate: "2026-09-07",
    dueDate: "2026-09-11",
    estimateMinutes: 480,
    assigneeName: "Ava Morgan",
    visibility: "internal",
    position: 1,
    version: 1,
    labels: [demoLabels[1]],
  },
  {
    id: "task-github",
    projectId: demoProject.id,
    statusId: "status-todo",
    statusName: "Todo",
    statusCategory: "todo",
    title: "GitHub connection & first import",
    description:
      "Connect the Northstar repository and review the initial issue mapping.",
    priority: "high",
    startDate: "2026-09-14",
    dueDate: "2026-09-25",
    estimateMinutes: 1200,
    assigneeName: "Jon Bell",
    visibility: "internal",
    position: 2,
    version: 1,
    labels: [demoLabels[1], demoLabels[3]],
  },
  {
    id: "task-content",
    projectId: demoProject.id,
    statusId: "status-blocked",
    statusName: "Blocked",
    statusCategory: "blocked",
    title: "Approve launch content",
    description: "Waiting for the final customer copy and product screenshots.",
    priority: "medium",
    startDate: "2026-09-21",
    dueDate: "2026-10-02",
    estimateMinutes: 720,
    assigneeName: "Priya Shah",
    visibility: "customer",
    position: 3,
    version: 2,
    labels: [demoLabels[0], demoLabels[2]],
  },
  {
    id: "task-launch",
    projectId: demoProject.id,
    statusId: "status-backlog",
    statusName: "Backlog",
    statusCategory: "backlog",
    title: "Launch handoff",
    description: "Document the final handoff and support checklist.",
    priority: "low",
    startDate: "2026-10-05",
    dueDate: "2026-10-16",
    estimateMinutes: 600,
    assigneeName: "Ava Morgan",
    visibility: "customer",
    position: 4,
    version: 1,
    labels: [demoLabels[2]],
  },
]

export const demoMilestones: Milestone[] = [
  {
    id: "milestone-foundation",
    projectId: demoProject.id,
    name: "Foundation ready",
    description:
      "The shared workspace and customer story are ready for review.",
    startDate: "2026-08-17",
    dueDate: "2026-09-04",
    status: "closed",
    visibility: "customer",
    version: 2,
  },
  {
    id: "milestone-beta",
    projectId: demoProject.id,
    name: "Customer beta",
    description: "A private customer review of the portal and connected work.",
    startDate: "2026-09-07",
    dueDate: "2026-09-25",
    status: "open",
    visibility: "customer",
    version: 1,
  },
  {
    id: "milestone-launch",
    projectId: demoProject.id,
    name: "Launch",
    description: "Production handoff and public status page go live.",
    startDate: "2026-10-05",
    dueDate: "2026-10-16",
    status: "open",
    visibility: "customer",
    version: 1,
  },
]

export const demoSession: Session = {
  user: {
    id: "user-ava",
    name: "Ava Morgan",
    email: "ava@justprojects.local",
    emailVerified: true,
  },
  tenant: {
    id: "tenant-justlab",
    name: "JustLab Studio",
    slug: "justlab-studio",
  },
  membership: { role: "owner" },
}

export const demoSyncEvents: SyncEvent[] = [
  {
    id: "sync-1",
    eventName: "github.issues",
    action: "synchronize",
    status: "succeeded",
    createdAt: "2026-09-01T08:42:00Z",
  },
  {
    id: "sync-2",
    eventName: "github.milestone",
    action: "update",
    status: "succeeded",
    createdAt: "2026-08-31T16:15:00Z",
  },
  {
    id: "sync-3",
    eventName: "github.issues",
    action: "update",
    status: "queued",
    createdAt: "2026-08-31T14:02:00Z",
  },
]

export const demoGitHubConnections: GitHubConnection[] = [
  {
    id: "github-demo",
    authMethod: "app",
    externalAccountLogin: "justlab-studio",
    scopes: ["issues:read", "issues:write", "metadata:read"],
    active: true,
  },
]

export const demoWorkspace: WorkspaceData = {
  project: demoProject,
  projects: demoProjects,
  statuses: demoStatuses,
  tasks: demoTasks,
  milestones: demoMilestones,
  labels: demoLabels,
  session: demoSession,
  syncEvents: demoSyncEvents,
  githubConnections: demoGitHubConnections,
}
