// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for GitHubConnectionAuthMethod.
const (
	App   GitHubConnectionAuthMethod = "app"
	Oauth GitHubConnectionAuthMethod = "oauth"
)

// Defines values for InvitationRole.
const (
	InvitationRoleAdmin  InvitationRole = "admin"
	InvitationRoleMember InvitationRole = "member"
	InvitationRoleViewer InvitationRole = "viewer"
)

// Defines values for InvitationRequestRole.
const (
	InvitationRequestRoleAdmin  InvitationRequestRole = "admin"
	InvitationRequestRoleMember InvitationRequestRole = "member"
	InvitationRequestRoleViewer InvitationRequestRole = "viewer"
)

// Defines values for MembershipRole.
const (
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleViewer MembershipRole = "viewer"
)

// Defines values for MilestoneStatus.
const (
	MilestoneStatusClosed MilestoneStatus = "closed"
	MilestoneStatusOpen   MilestoneStatus = "open"
)

// Defines values for MilestoneVisibility.
const (
	MilestoneVisibilityCustomer MilestoneVisibility = "customer"
	MilestoneVisibilityInternal MilestoneVisibility = "internal"
)

// Defines values for MilestonePatchStatus.
const (
	MilestonePatchStatusClosed MilestonePatchStatus = "closed"
	MilestonePatchStatusOpen   MilestonePatchStatus = "open"
)

// Defines values for MilestonePatchVisibility.
const (
	MilestonePatchVisibilityCustomer MilestonePatchVisibility = "customer"
	MilestonePatchVisibilityInternal MilestonePatchVisibility = "internal"
)

// Defines values for MilestoneRequestStatus.
const (
	MilestoneRequestStatusClosed MilestoneRequestStatus = "closed"
	MilestoneRequestStatusOpen   MilestoneRequestStatus = "open"
)

// Defines values for MilestoneRequestVisibility.
const (
	MilestoneRequestVisibilityCustomer MilestoneRequestVisibility = "customer"
	MilestoneRequestVisibilityInternal MilestoneRequestVisibility = "internal"
)

// Defines values for PermissionGrantEffect.
const (
	PermissionGrantEffectAllow PermissionGrantEffect = "allow"
	PermissionGrantEffectDeny  PermissionGrantEffect = "deny"
)

// Defines values for PermissionGrantRequestEffect.
const (
	PermissionGrantRequestEffectAllow PermissionGrantRequestEffect = "allow"
	PermissionGrantRequestEffectDeny  PermissionGrantRequestEffect = "deny"
)

// Defines values for PublicMilestoneStatus.
const (
	PublicMilestoneStatusClosed PublicMilestoneStatus = "closed"
	PublicMilestoneStatusOpen   PublicMilestoneStatus = "open"
)

// Defines values for PublicPageAccessMode.
const (
	PublicPageAccessModeLink  PublicPageAccessMode = "link"
	PublicPageAccessModeLogin PublicPageAccessMode = "login"
)

// Defines values for PublicPageRequestAccessMode.
const (
	PublicPageRequestAccessModeLink  PublicPageRequestAccessMode = "link"
	PublicPageRequestAccessModeLogin PublicPageRequestAccessMode = "login"
)

// Defines values for PublicTaskPriority.
const (
	PublicTaskPriorityHigh   PublicTaskPriority = "high"
	PublicTaskPriorityLow    PublicTaskPriority = "low"
	PublicTaskPriorityMedium PublicTaskPriority = "medium"
	PublicTaskPriorityUrgent PublicTaskPriority = "urgent"
)

// Defines values for StatusCategory.
const (
	Backlog    StatusCategory = "backlog"
	Blocked    StatusCategory = "blocked"
	Done       StatusCategory = "done"
	InProgress StatusCategory = "in_progress"
	Todo       StatusCategory = "todo"
)

// Defines values for SyncConflictStatus.
const (
	SyncConflictStatusIgnored  SyncConflictStatus = "ignored"
	SyncConflictStatusOpen     SyncConflictStatus = "open"
	SyncConflictStatusResolved SyncConflictStatus = "resolved"
)

// Defines values for SyncEventStatus.
const (
	SyncEventStatusFailed     SyncEventStatus = "failed"
	SyncEventStatusProcessing SyncEventStatus = "processing"
	SyncEventStatusQueued     SyncEventStatus = "queued"
	SyncEventStatusSucceeded  SyncEventStatus = "succeeded"
)

// Defines values for TaskPriority.
const (
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// Defines values for TaskVisibility.
const (
	TaskVisibilityCustomer TaskVisibility = "customer"
	TaskVisibilityInternal TaskVisibility = "internal"
)

// Defines values for TaskPatchPriority.
const (
	TaskPatchPriorityHigh   TaskPatchPriority = "high"
	TaskPatchPriorityLow    TaskPatchPriority = "low"
	TaskPatchPriorityMedium TaskPatchPriority = "medium"
	TaskPatchPriorityUrgent TaskPatchPriority = "urgent"
)

// Defines values for TaskPatchVisibility.
const (
	TaskPatchVisibilityCustomer TaskPatchVisibility = "customer"
	TaskPatchVisibilityInternal TaskPatchVisibility = "internal"
)

// Defines values for TaskRequestPriority.
const (
	TaskRequestPriorityHigh   TaskRequestPriority = "high"
	TaskRequestPriorityLow    TaskRequestPriority = "low"
	TaskRequestPriorityMedium TaskRequestPriority = "medium"
	TaskRequestPriorityUrgent TaskRequestPriority = "urgent"
)

// Defines values for TaskRequestVisibility.
const (
	TaskRequestVisibilityCustomer TaskRequestVisibility = "customer"
	TaskRequestVisibilityInternal TaskRequestVisibility = "internal"
)

// Defines values for SyncStatus.
const (
	SyncStatusFailed     SyncStatus = "failed"
	SyncStatusProcessing SyncStatus = "processing"
	SyncStatusQueued     SyncStatus = "queued"
	SyncStatusSucceeded  SyncStatus = "succeeded"
)

// Defines values for ListSyncConflictsParamsStatus.
const (
	ListSyncConflictsParamsStatusIgnored  ListSyncConflictsParamsStatus = "ignored"
	ListSyncConflictsParamsStatusOpen     ListSyncConflictsParamsStatus = "open"
	ListSyncConflictsParamsStatusResolved ListSyncConflictsParamsStatus = "resolved"
)

// Defines values for ResolveSyncConflictJSONBodyResolution.
const (
	Ignore ResolveSyncConflictJSONBodyResolution = "ignore"
	Local  ResolveSyncConflictJSONBodyResolution = "local"
	Remote ResolveSyncConflictJSONBodyResolution = "remote"
)

// Defines values for ListSyncRunsParamsStatus.
const (
	Failed     ListSyncRunsParamsStatus = "failed"
	Processing ListSyncRunsParamsStatus = "processing"
	Queued     ListSyncRunsParamsStatus = "queued"
	Succeeded  ListSyncRunsParamsStatus = "succeeded"
)

// Defines values for UpdateTenantMemberJSONBodyRole.
const (
	UpdateTenantMemberJSONBodyRoleAdmin  UpdateTenantMemberJSONBodyRole = "admin"
	UpdateTenantMemberJSONBodyRoleMember UpdateTenantMemberJSONBodyRole = "member"
	UpdateTenantMemberJSONBodyRoleViewer UpdateTenantMemberJSONBodyRole = "viewer"
)

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                 `json:"action"`
	ActorId    *openapi_types.UUID    `json:"actorId"`
	CreatedAt  *time.Time             `json:"createdAt,omitempty"`
	EntityId   openapi_types.UUID     `json:"entityId"`
	EntityType string                 `json:"entityType"`
	Id         openapi_types.UUID     `json:"id"`
	Metadata   map[string]interface{} `json:"metadata"`
	TenantId   openapi_types.UUID     `json:"tenantId"`
}

// AuditEventList defines model for AuditEventList.
type AuditEventList struct {
	Count *int          `json:"count,omitempty"`
	Items *[]AuditEvent `json:"items,omitempty"`
}

// ConflictList defines model for ConflictList.
type ConflictList struct {
	Count *int            `json:"count,omitempty"`
	Items *[]SyncConflict `json:"items,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// GitHubConnection defines model for GitHubConnection.
type GitHubConnection struct {
	Active               bool                       `json:"active"`
	AuthMethod           GitHubConnectionAuthMethod `json:"authMethod"`
	ExternalAccountId    int64                      `json:"externalAccountId"`
	ExternalAccountLogin *string                    `json:"externalAccountLogin,omitempty"`
	Id                   openapi_types.UUID         `json:"id"`
	InstallationId       *int64                     `json:"installationId"`
	Scopes               []string                   `json:"scopes"`
	TenantId             openapi_types.UUID         `json:"tenantId"`
}

// GitHubConnectionAuthMethod defines model for GitHubConnection.AuthMethod.
type GitHubConnectionAuthMethod string

// GitHubRepository defines model for GitHubRepository.
type GitHubRepository struct {
	ConnectionId openapi_types.UUID `json:"connectionId"`
	ExternalId   int64              `json:"externalId"`
	FullName     string             `json:"fullName"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	Owner        string             `json:"owner"`
	Private      bool               `json:"private"`
}

// GitHubUserMapping defines model for GitHubUserMapping.
type GitHubUserMapping struct {
	GithubLogin string             `json:"githubLogin"`
	Id          openapi_types.UUID `json:"id"`
	TenantId    openapi_types.UUID `json:"tenantId"`
	UserId      openapi_types.UUID `json:"userId"`
}

// GitHubUserMappingList defines model for GitHubUserMappingList.
type GitHubUserMappingList struct {
	Count *int                 `json:"count,omitempty"`
	Items *[]GitHubUserMapping `json:"items,omitempty"`
}

// GitHubUserMappingRequest defines model for GitHubUserMappingRequest.
type GitHubUserMappingRequest struct {
	GithubLogin string             `json:"githubLogin"`
	UserId      openapi_types.UUID `json:"userId"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	AcceptedAt *time.Time          `json:"acceptedAt"`
	Email      openapi_types.Email `json:"email"`
	ExpiresAt  time.Time           `json:"expiresAt"`
	Id         openapi_types.UUID  `json:"id"`
	Role       InvitationRole      `json:"role"`
	TenantId   openapi_types.UUID  `json:"tenantId"`
}

// InvitationRole defines model for Invitation.Role.
type InvitationRole string

// InvitationCreated defines model for InvitationCreated.
type InvitationCreated struct {
	AcceptUrl  string     `json:"acceptUrl"`
	Invitation Invitation `json:"invitation"`
	Token      string     `json:"token"`
}

// InvitationList defines model for InvitationList.
type InvitationList struct {
	Count *int          `json:"count,omitempty"`
	Items *[]Invitation `json:"items,omitempty"`
}

// InvitationRequest defines model for InvitationRequest.
type InvitationRequest struct {
	Email openapi_types.Email    `json:"email"`
	Role  *InvitationRequestRole `json:"role,omitempty"`
}

// InvitationRequestRole defines model for InvitationRequest.Role.
type InvitationRequestRole string

// Label defines model for Label.
type Label struct {
	Color     string              `json:"color"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	ProjectId *openapi_types.UUID `json:"projectId"`
	TenantId  openapi_types.UUID  `json:"tenantId"`
}

// LabelList defines model for LabelList.
type LabelList struct {
	Items *[]Label `json:"items,omitempty"`
}

// LabelRequest defines model for LabelRequest.
type LabelRequest struct {
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`
}

// Membership defines model for Membership.
type Membership struct {
	Id       openapi_types.UUID `json:"id"`
	Role     MembershipRole     `json:"role"`
	TenantId openapi_types.UUID `json:"tenantId"`
	UserId   openapi_types.UUID `json:"userId"`
}

// MembershipRole defines model for Membership.Role.
type MembershipRole string

// Milestone defines model for Milestone.
type Milestone struct {
	Description *string             `json:"description,omitempty"`
	DueDate     *openapi_types.Date `json:"dueDate"`
	Id          openapi_types.UUID  `json:"id"`
	Name        string              `json:"name"`
	ProjectId   openapi_types.UUID  `json:"projectId"`
	StartDate   *openapi_types.Date `json:"startDate"`
	Status      MilestoneStatus     `json:"status"`
	TenantId    openapi_types.UUID  `json:"tenantId"`
	Version     int64               `json:"version"`
	Visibility  MilestoneVisibility `json:"visibility"`
}

// MilestoneStatus defines model for Milestone.Status.
type MilestoneStatus string

// MilestoneVisibility defines model for Milestone.Visibility.
type MilestoneVisibility string

// MilestoneList defines model for MilestoneList.
type MilestoneList struct {
	Count *int         `json:"count,omitempty"`
	Items *[]Milestone `json:"items,omitempty"`
}

// MilestonePatch defines model for MilestonePatch.
type MilestonePatch struct {
	Description *string                   `json:"description,omitempty"`
	DueDate     *openapi_types.Date       `json:"dueDate,omitempty"`
	Name        string                    `json:"name"`
	StartDate   *openapi_types.Date       `json:"startDate,omitempty"`
	Status      *MilestonePatchStatus     `json:"status,omitempty"`
	Version     *int64                    `json:"version,omitempty"`
	Visibility  *MilestonePatchVisibility `json:"visibility,omitempty"`
}

// MilestonePatchStatus defines model for MilestonePatch.Status.
type MilestonePatchStatus string

// MilestonePatchVisibility defines model for MilestonePatch.Visibility.
type MilestonePatchVisibility string

// MilestoneRequest defines model for MilestoneRequest.
type MilestoneRequest struct {
	Description *string                     `json:"description,omitempty"`
	DueDate     *openapi_types.Date         `json:"dueDate,omitempty"`
	Name        string                      `json:"name"`
	StartDate   *openapi_types.Date         `json:"startDate,omitempty"`
	Status      *MilestoneRequestStatus     `json:"status,omitempty"`
	Visibility  *MilestoneRequestVisibility `json:"visibility,omitempty"`
}

// MilestoneRequestStatus defines model for MilestoneRequest.Status.
type MilestoneRequestStatus string

// MilestoneRequestVisibility defines model for MilestoneRequest.Visibility.
type MilestoneRequestVisibility string

// PermissionGrant defines model for PermissionGrant.
type PermissionGrant struct {
	Effect     PermissionGrantEffect `json:"effect"`
	Id         openapi_types.UUID    `json:"id"`
	Permission string                `json:"permission"`
	ProjectId  *openapi_types.UUID   `json:"projectId"`
	TenantId   openapi_types.UUID    `json:"tenantId"`
	UserId     openapi_types.UUID    `json:"userId"`
}

// PermissionGrantEffect defines model for PermissionGrant.Effect.
type PermissionGrantEffect string

// PermissionGrantList defines model for PermissionGrantList.
type PermissionGrantList struct {
	Count *int               `json:"count,omitempty"`
	Items *[]PermissionGrant `json:"items,omitempty"`
}

// PermissionGrantRequest defines model for PermissionGrantRequest.
type PermissionGrantRequest struct {
	Effect     *PermissionGrantRequestEffect `json:"effect,omitempty"`
	Permission string                        `json:"permission"`
	ProjectId  *openapi_types.UUID           `json:"projectId"`
	UserId     openapi_types.UUID            `json:"userId"`
}

// PermissionGrantRequestEffect defines model for PermissionGrantRequest.Effect.
type PermissionGrantRequestEffect string

// Project defines model for Project.
type Project struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Key         string              `json:"key"`
	Name        string              `json:"name"`
	StartDate   *openapi_types.Date `json:"startDate"`
	Status      string              `json:"status"`
	TargetDate  *openapi_types.Date `json:"targetDate"`
	TenantId    openapi_types.UUID  `json:"tenantId"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
	Version     int64               `json:"version"`
}

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Count *int       `json:"count,omitempty"`
	Items *[]Project `json:"items,omitempty"`
}

// ProjectPatch defines model for ProjectPatch.
type ProjectPatch struct {
	Description *string             `json:"description,omitempty"`
	Key         *string             `json:"key,omitempty"`
	Name        string              `json:"name"`
	StartDate   *openapi_types.Date `json:"startDate,omitempty"`
	TargetDate  *openapi_types.Date `json:"targetDate,omitempty"`
	Version     *int64              `json:"version,omitempty"`
}

// ProjectRepository defines model for ProjectRepository.
type ProjectRepository struct {
	Link struct {
		Id           *openapi_types.UUID `json:"id,omitempty"`
		ProjectId    *openapi_types.UUID `json:"projectId,omitempty"`
		RepositoryId *openapi_types.UUID `json:"repositoryId,omitempty"`
	} `json:"link"`
	Repository GitHubRepository `json:"repository"`
}

// ProjectRepositoryList defines model for ProjectRepositoryList.
type ProjectRepositoryList struct {
	Count *int                 `json:"count,omitempty"`
	Items *[]ProjectRepository `json:"items,omitempty"`
}

// ProjectRequest defines model for ProjectRequest.
type ProjectRequest struct {
	Description *string             `json:"description,omitempty"`
	Key         *string             `json:"key,omitempty"`
	Name        string              `json:"name"`
	StartDate   *openapi_types.Date `json:"startDate,omitempty"`
	TargetDate  *openapi_types.Date `json:"targetDate,omitempty"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus struct {
	Category  StatusCategory     `json:"category"`
	Color     *string            `json:"color,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Position  int                `json:"position"`
	ProjectId openapi_types.UUID `json:"projectId"`
}

// PublicMilestone defines model for PublicMilestone.
type PublicMilestone struct {
	Description *string               `json:"description,omitempty"`
	DueDate     *openapi_types.Date   `json:"dueDate"`
	Id          openapi_types.UUID    `json:"id"`
	Name        string                `json:"name"`
	StartDate   *openapi_types.Date   `json:"startDate"`
	Status      PublicMilestoneStatus `json:"status"`
}

// PublicMilestoneStatus defines model for PublicMilestone.Status.
type PublicMilestoneStatus string

// PublicPage defines model for PublicPage.
type PublicPage struct {
	AccessMode          PublicPageAccessMode  `json:"accessMode"`
	Id                  openapi_types.UUID    `json:"id"`
	ProjectId           openapi_types.UUID    `json:"projectId"`
	Revoked             bool                  `json:"revoked"`
	Slug                string                `json:"slug"`
	TenantId            openapi_types.UUID    `json:"tenantId"`
	Title               *string               `json:"title,omitempty"`
	VisibleMilestoneIds *[]openapi_types.UUID `json:"visibleMilestoneIds,omitempty"`
	VisibleTaskIds      *[]openapi_types.UUID `json:"visibleTaskIds,omitempty"`
}

// PublicPageAccessMode defines model for PublicPage.AccessMode.
type PublicPageAccessMode string

// PublicPageCreated defines model for PublicPageCreated.
type PublicPageCreated struct {
	Page  PublicPage `json:"page"`
	Token string     `json:"token"`
	Url   string     `json:"url"`
}

// PublicPageList defines model for PublicPageList.
type PublicPageList struct {
	Items *[]PublicPage `json:"items,omitempty"`
}

// PublicPagePayload defines model for PublicPagePayload.
type PublicPagePayload struct {
	Milestones []PublicMilestone `json:"milestones"`
	Page       struct {
		AccessMode *string `json:"accessMode,omitempty"`
		Title      *string `json:"title,omitempty"`
	} `json:"page"`
	Project struct {
		Description *string             `json:"description,omitempty"`
		Key         *string             `json:"key,omitempty"`
		Name        *string             `json:"name,omitempty"`
		TargetDate  *openapi_types.Date `json:"targetDate"`
	} `json:"project"`
	Tasks []PublicTask `json:"tasks"`
}

// PublicPageRequest defines model for PublicPageRequest.
type PublicPageRequest struct {
	AccessMode          *PublicPageRequestAccessMode `json:"accessMode,omitempty"`
	Title               *string                      `json:"title,omitempty"`
	ViewerUserIds       *[]openapi_types.UUID        `json:"viewerUserIds,omitempty"`
	VisibleMilestoneIds *[]openapi_types.UUID        `json:"visibleMilestoneIds,omitempty"`
	VisibleTaskIds      *[]openapi_types.UUID        `json:"visibleTaskIds,omitempty"`
}

// PublicPageRequestAccessMode defines model for PublicPageRequest.AccessMode.
type PublicPageRequestAccessMode string

// PublicPageViewer defines model for PublicPageViewer.
type PublicPageViewer struct {
	Id           openapi_types.UUID `json:"id"`
	PublicPageId openapi_types.UUID `json:"publicPageId"`
	UserId       openapi_types.UUID `json:"userId"`
}

// PublicTask defines model for PublicTask.
type PublicTask struct {
	Description     *string             `json:"description,omitempty"`
	DueDate         *openapi_types.Date `json:"dueDate"`
	EstimateMinutes *int                `json:"estimateMinutes"`
	Id              openapi_types.UUID  `json:"id"`
	MilestoneId     *openapi_types.UUID `json:"milestoneId"`
	ParentId        *openapi_types.UUID `json:"parentId"`
	Priority        PublicTaskPriority  `json:"priority"`
	StartDate       *openapi_types.Date `json:"startDate"`
	StatusCategory  StatusCategory      `json:"statusCategory"`
	StatusName      string              `json:"statusName"`
	Title           string              `json:"title"`
}

// PublicTaskPriority defines model for PublicTask.Priority.
type PublicTaskPriority string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email      openapi_types.Email `json:"email"`
	Name       string              `json:"name"`
	Password   string              `json:"password"`
	TenantName string              `json:"tenantName"`
}

// Session defines model for Session.
type Session struct {
	Membership Membership `json:"membership"`
	Tenant     Tenant     `json:"tenant"`
	User       User       `json:"user"`
}

// StatusCategory defines model for StatusCategory.
type StatusCategory string

// StatusRequest defines model for StatusRequest.
type StatusRequest struct {
	Category *StatusCategory `json:"category,omitempty"`
	Color    *string         `json:"color,omitempty"`
	Name     *string         `json:"name,omitempty"`
	Position *int            `json:"position,omitempty"`
}

// SyncConflict defines model for SyncConflict.
type SyncConflict struct {
	DeliveryId      *string            `json:"deliveryId,omitempty"`
	ExternalLinkId  openapi_types.UUID `json:"externalLinkId"`
	Field           string             `json:"field"`
	Id              openapi_types.UUID `json:"id"`
	LocalChangedAt  time.Time          `json:"localChangedAt"`
	LocalValue      interface{}        `json:"localValue"`
	RemoteChangedAt time.Time          `json:"remoteChangedAt"`
	RemoteValue     interface{}        `json:"remoteValue"`
	Resolution      *string            `json:"resolution,omitempty"`
	Status          SyncConflictStatus `json:"status"`
	TenantId        openapi_types.UUID `json:"tenantId"`
}

// SyncConflictStatus defines model for SyncConflict.Status.
type SyncConflictStatus string

// SyncEvent defines model for SyncEvent.
type SyncEvent struct {
	Action       *string                `json:"action,omitempty"`
	ConnectionId *openapi_types.UUID    `json:"connectionId"`
	CreatedAt    *time.Time             `json:"createdAt,omitempty"`
	DeliveryId   string                 `json:"deliveryId"`
	ErrorMessage *string                `json:"errorMessage,omitempty"`
	EventName    string                 `json:"eventName"`
	Id           openapi_types.UUID     `json:"id"`
	Payload      map[string]interface{} `json:"payload"`
	Status       SyncEventStatus        `json:"status"`
	TenantId     *openapi_types.UUID    `json:"tenantId"`
	UpdatedAt    *time.Time             `json:"updatedAt,omitempty"`
}

// SyncEventStatus defines model for SyncEvent.Status.
type SyncEventStatus string

// SyncEventList defines model for SyncEventList.
type SyncEventList struct {
	Count *int         `json:"count,omitempty"`
	Items *[]SyncEvent `json:"items,omitempty"`
}

// Task defines model for Task.
type Task struct {
	AssigneeId      *openapi_types.UUID `json:"assigneeId"`
	AssigneeName    *string             `json:"assigneeName,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Description     *string             `json:"description,omitempty"`
	DueDate         *openapi_types.Date `json:"dueDate"`
	EstimateMinutes *int                `json:"estimateMinutes"`
	Id              openapi_types.UUID  `json:"id"`
	Labels          *[]Label            `json:"labels,omitempty"`
	MilestoneId     *openapi_types.UUID `json:"milestoneId"`
	ParentId        *openapi_types.UUID `json:"parentId"`
	Position        *int                `json:"position,omitempty"`
	Priority        TaskPriority        `json:"priority"`
	ProjectId       openapi_types.UUID  `json:"projectId"`
	StartDate       *openapi_types.Date `json:"startDate"`
	StatusCategory  *StatusCategory     `json:"statusCategory,omitempty"`
	StatusId        openapi_types.UUID  `json:"statusId"`
	StatusName      *string             `json:"statusName,omitempty"`
	TenantId        openapi_types.UUID  `json:"tenantId"`
	Title           string              `json:"title"`
	UpdatedAt       *time.Time          `json:"updatedAt,omitempty"`
	Version         int64               `json:"version"`
	Visibility      TaskVisibility      `json:"visibility"`
}

// TaskPriority defines model for Task.Priority.
type TaskPriority string

// TaskVisibility defines model for Task.Visibility.
type TaskVisibility string

// TaskList defines model for TaskList.
type TaskList struct {
	Count *int    `json:"count,omitempty"`
	Items *[]Task `json:"items,omitempty"`
}

// TaskPatch defines model for TaskPatch.
type TaskPatch struct {
	AssigneeId      *openapi_types.UUID   `json:"assigneeId"`
	Description     *string               `json:"description,omitempty"`
	DueDate         *openapi_types.Date   `json:"dueDate,omitempty"`
	EstimateMinutes *int                  `json:"estimateMinutes,omitempty"`
	LabelIds        *[]openapi_types.UUID `json:"labelIds,omitempty"`
	MilestoneId     *openapi_types.UUID   `json:"milestoneId"`
	ParentId        *openapi_types.UUID   `json:"parentId"`
	Position        *int                  `json:"position,omitempty"`
	Priority        *TaskPatchPriority    `json:"priority,omitempty"`
	StartDate       *openapi_types.Date   `json:"startDate,omitempty"`
	StatusId        *openapi_types.UUID   `json:"statusId,omitempty"`
	Title           string                `json:"title"`
	Version         *int64                `json:"version,omitempty"`
	Visibility      *TaskPatchVisibility  `json:"visibility,omitempty"`
}

// TaskPatchPriority defines model for TaskPatch.Priority.
type TaskPatchPriority string

// TaskPatchVisibility defines model for TaskPatch.Visibility.
type TaskPatchVisibility string

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	AssigneeId      *openapi_types.UUID    `json:"assigneeId"`
	Description     *string                `json:"description,omitempty"`
	DueDate         *openapi_types.Date    `json:"dueDate,omitempty"`
	EstimateMinutes *int                   `json:"estimateMinutes,omitempty"`
	LabelIds        *[]openapi_types.UUID  `json:"labelIds,omitempty"`
	MilestoneId     *openapi_types.UUID    `json:"milestoneId"`
	ParentId        *openapi_types.UUID    `json:"parentId"`
	Position        *int                   `json:"position,omitempty"`
	Priority        *TaskRequestPriority   `json:"priority,omitempty"`
	StartDate       *openapi_types.Date    `json:"startDate,omitempty"`
	StatusId        *openapi_types.UUID    `json:"statusId,omitempty"`
	Title           string                 `json:"title"`
	Visibility      *TaskRequestVisibility `json:"visibility,omitempty"`
}

// TaskRequestPriority defines model for TaskRequest.Priority.
type TaskRequestPriority string

// TaskRequestVisibility defines model for TaskRequest.Visibility.
type TaskRequestVisibility string

// Tenant defines model for Tenant.
type Tenant struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// TenantMember defines model for TenantMember.
type TenantMember struct {
	Membership Membership `json:"membership"`
	User       User       `json:"user"`
}

// User defines model for User.
type User struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified *bool               `json:"emailVerified,omitempty"`
	Id            openapi_types.UUID  `json:"id"`
	Name          string              `json:"name"`
}

// ConflictId defines model for ConflictId.
type ConflictId = openapi_types.UUID

// GrantId defines model for GrantId.
type GrantId = openapi_types.UUID

// InvitationToken defines model for InvitationToken.
type InvitationToken = string

// Limit defines model for Limit.
type Limit = int

// MappingId defines model for MappingId.
type MappingId = openapi_types.UUID

// MilestoneId defines model for MilestoneId.
type MilestoneId = openapi_types.UUID

// MilestoneQuery defines model for MilestoneQuery.
type MilestoneQuery = openapi_types.UUID

// OIDCCode defines model for OIDCCode.
type OIDCCode = string

// OIDCState defines model for OIDCState.
type OIDCState = string

// PageId defines model for PageId.
type PageId = openapi_types.UUID

// PageSlug defines model for PageSlug.
type PageSlug = string

// ProjectId defines model for ProjectId.
type ProjectId = openapi_types.UUID

// ProjectQuery defines model for ProjectQuery.
type ProjectQuery = openapi_types.UUID

// PublicToken defines model for PublicToken.
type PublicToken = string

// Query defines model for Query.
type Query = string

// RepositoryId defines model for RepositoryId.
type RepositoryId = openapi_types.UUID

// StatusId defines model for StatusId.
type StatusId = openapi_types.UUID

// StatusQuery defines model for StatusQuery.
type StatusQuery = openapi_types.UUID

// SyncStatus defines model for SyncStatus.
type SyncStatus string

// TaskId defines model for TaskId.
type TaskId = openapi_types.UUID

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// UserQuery defines model for UserQuery.
type UserQuery = openapi_types.UUID

// TenantWithMembers defines model for TenantWithMembers.
type TenantWithMembers struct {
	Members []TenantMember `json:"members"`
	Tenant  Tenant         `json:"tenant"`
}

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CompleteOIDCParams defines parameters for CompleteOIDC.
type CompleteOIDCParams struct {
	State OIDCState `form:"state" json:"state"`
	Code  OIDCCode  `form:"code" json:"code"`
}

// CompleteGitHubAppInstallParams defines parameters for CompleteGitHubAppInstall.
type CompleteGitHubAppInstallParams struct {
	State          OIDCState `form:"state" json:"state"`
	InstallationId int64     `form:"installation_id" json:"installation_id"`
}

// CompleteGitHubOAuthParams defines parameters for CompleteGitHubOAuth.
type CompleteGitHubOAuthParams struct {
	State OIDCState `form:"state" json:"state"`
	Code  OIDCCode  `form:"code" json:"code"`
}

// ImportGitHubProjectJSONBody defines parameters for ImportGitHubProject.
type ImportGitHubProjectJSONBody struct {
	RepositoryId *openapi_types.UUID `json:"repositoryId,omitempty"`
}

// AttachProjectRepositoryJSONBody defines parameters for AttachProjectRepository.
type AttachProjectRepositoryJSONBody struct {
	RepositoryId openapi_types.UUID `json:"repositoryId"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	Q           *Query          `form:"q,omitempty" json:"q,omitempty"`
	StatusId    *StatusQuery    `form:"statusId,omitempty" json:"statusId,omitempty"`
	MilestoneId *MilestoneQuery `form:"milestoneId,omitempty" json:"milestoneId,omitempty"`
}

// AddPublicPageViewerJSONBody defines parameters for AddPublicPageViewer.
type AddPublicPageViewerJSONBody struct {
	UserId openapi_types.UUID `json:"userId"`
}

// GetPublicPageParams defines parameters for GetPublicPage.
type GetPublicPageParams struct {
	Token *PublicToken `form:"token,omitempty" json:"token,omitempty"`
}

// ListSyncConflictsParams defines parameters for ListSyncConflicts.
type ListSyncConflictsParams struct {
	Status    *ListSyncConflictsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	ProjectId *ProjectQuery                  `form:"projectId,omitempty" json:"projectId,omitempty"`
}

// ListSyncConflictsParamsStatus defines parameters for ListSyncConflicts.
type ListSyncConflictsParamsStatus string

// ResolveSyncConflictJSONBody defines parameters for ResolveSyncConflict.
type ResolveSyncConflictJSONBody struct {
	Resolution ResolveSyncConflictJSONBodyResolution `json:"resolution"`
}

// ResolveSyncConflictJSONBodyResolution defines parameters for ResolveSyncConflict.
type ResolveSyncConflictJSONBodyResolution string

// ListSyncRunsParams defines parameters for ListSyncRuns.
type ListSyncRunsParams struct {
	Status *ListSyncRunsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit                    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSyncRunsParamsStatus defines parameters for ListSyncRuns.
type ListSyncRunsParamsStatus string

// UpdateTenantMemberJSONBody defines parameters for UpdateTenantMember.
type UpdateTenantMemberJSONBody struct {
	Role UpdateTenantMemberJSONBodyRole `json:"role"`
}

// UpdateTenantMemberJSONBodyRole defines parameters for UpdateTenantMember.
type UpdateTenantMemberJSONBodyRole string

// ListPermissionGrantsParams defines parameters for ListPermissionGrants.
type ListPermissionGrantsParams struct {
	UserId    *UserQuery    `form:"userId,omitempty" json:"userId,omitempty"`
	ProjectId *ProjectQuery `form:"projectId,omitempty" json:"projectId,omitempty"`
}

// ReceiveGitHubWebhookJSONBody defines parameters for ReceiveGitHubWebhook.
type ReceiveGitHubWebhookJSONBody map[string]interface{}

// ReceiveGitHubWebhookParams defines parameters for ReceiveGitHubWebhook.
type ReceiveGitHubWebhookParams struct {
	XHubSignature256 string `json:"X-Hub-Signature-256"`
	XGitHubDelivery  string `json:"X-GitHub-Delivery"`
	XGitHubEvent     string `json:"X-GitHub-Event"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LoginCustomerJSONRequestBody defines body for LoginCustomer for application/json ContentType.
type LoginCustomerJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateGitHubUserMappingJSONRequestBody defines body for CreateGitHubUserMapping for application/json ContentType.
type CreateGitHubUserMappingJSONRequestBody = GitHubUserMappingRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectPatch

// ImportGitHubProjectJSONRequestBody defines body for ImportGitHubProject for application/json ContentType.
type ImportGitHubProjectJSONRequestBody ImportGitHubProjectJSONBody

// CreateLabelJSONRequestBody defines body for CreateLabel for application/json ContentType.
type CreateLabelJSONRequestBody = LabelRequest

// CreateMilestoneJSONRequestBody defines body for CreateMilestone for application/json ContentType.
type CreateMilestoneJSONRequestBody = MilestoneRequest

// UpdateMilestoneJSONRequestBody defines body for UpdateMilestone for application/json ContentType.
type UpdateMilestoneJSONRequestBody = MilestonePatch

// CreatePublicPageJSONRequestBody defines body for CreatePublicPage for application/json ContentType.
type CreatePublicPageJSONRequestBody = PublicPageRequest

// AttachProjectRepositoryJSONRequestBody defines body for AttachProjectRepository for application/json ContentType.
type AttachProjectRepositoryJSONRequestBody AttachProjectRepositoryJSONBody

// CreateStatusJSONRequestBody defines body for CreateStatus for application/json ContentType.
type CreateStatusJSONRequestBody = StatusRequest

// UpdateStatusJSONRequestBody defines body for UpdateStatus for application/json ContentType.
type UpdateStatusJSONRequestBody = StatusRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = TaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = TaskPatch

// AddPublicPageViewerJSONRequestBody defines body for AddPublicPageViewer for application/json ContentType.
type AddPublicPageViewerJSONRequestBody AddPublicPageViewerJSONBody

// ResolveSyncConflictJSONRequestBody defines body for ResolveSyncConflict for application/json ContentType.
type ResolveSyncConflictJSONRequestBody ResolveSyncConflictJSONBody

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = InvitationRequest

// UpdateTenantMemberJSONRequestBody defines body for UpdateTenantMember for application/json ContentType.
type UpdateTenantMemberJSONRequestBody UpdateTenantMemberJSONBody

// CreatePermissionGrantJSONRequestBody defines body for CreatePermissionGrant for application/json ContentType.
type CreatePermissionGrantJSONRequestBody = PermissionGrantRequest

// ReceiveGitHubWebhookJSONRequestBody defines body for ReceiveGitHubWebhook for application/json ContentType.
type ReceiveGitHubWebhookJSONRequestBody ReceiveGitHubWebhookJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /audit/events)
	ListAuditEvents(c *gin.Context, params ListAuditEventsParams)

	// (POST /auth/login)
	Login(c *gin.Context)

	// (POST /auth/logout)
	Logout(c *gin.Context)

	// (GET /auth/oidc/callback)
	CompleteOIDC(c *gin.Context, params CompleteOIDCParams)

	// (GET /auth/oidc/start)
	StartOIDC(c *gin.Context)

	// (POST /auth/public/pages/{slug}/login)
	LoginCustomer(c *gin.Context, slug PageSlug)

	// (POST /auth/register)
	Register(c *gin.Context)

	// (GET /auth/session)
	GetSession(c *gin.Context)

	// (GET /healthz)
	Health(c *gin.Context)

	// (GET /integrations/github/app/callback)
	CompleteGitHubAppInstall(c *gin.Context, params CompleteGitHubAppInstallParams)

	// (GET /integrations/github/app/install)
	StartGitHubAppInstall(c *gin.Context)

	// (GET /integrations/github/connections)
	ListGitHubConnections(c *gin.Context)

	// (GET /integrations/github/oauth/callback)
	CompleteGitHubOAuth(c *gin.Context, params CompleteGitHubOAuthParams)

	// (GET /integrations/github/oauth/start)
	StartGitHubOAuth(c *gin.Context)

	// (GET /integrations/github/repositories)
	ListGitHubRepositories(c *gin.Context)

	// (GET /integrations/github/user-mappings)
	ListGitHubUserMappings(c *gin.Context)

	// (POST /integrations/github/user-mappings)
	CreateGitHubUserMapping(c *gin.Context)

	// (DELETE /integrations/github/user-mappings/{mappingId})
	DeleteGitHubUserMapping(c *gin.Context, mappingId MappingId)

	// (GET /me)
	GetCurrentPrincipal(c *gin.Context)

	// (GET /projects)
	ListProjects(c *gin.Context)

	// (POST /projects)
	CreateProject(c *gin.Context)

	// (GET /projects/{projectId})
	GetProject(c *gin.Context, projectId ProjectId)

	// (PATCH /projects/{projectId})
	UpdateProject(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/github/import)
	ImportGitHubProject(c *gin.Context, projectId ProjectId)

	// (GET /projects/{projectId}/labels)
	ListLabels(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/labels)
	CreateLabel(c *gin.Context, projectId ProjectId)

	// (GET /projects/{projectId}/milestones)
	ListMilestones(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/milestones)
	CreateMilestone(c *gin.Context, projectId ProjectId)

	// (PATCH /projects/{projectId}/milestones/{milestoneId})
	UpdateMilestone(c *gin.Context, projectId ProjectId, milestoneId MilestoneId)

	// (GET /projects/{projectId}/public-pages)
	ListPublicPages(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/public-pages)
	CreatePublicPage(c *gin.Context, projectId ProjectId)

	// (GET /projects/{projectId}/repositories)
	ListProjectRepositories(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/repositories)
	AttachProjectRepository(c *gin.Context, projectId ProjectId)

	// (DELETE /projects/{projectId}/repositories/{repositoryId})
	DetachProjectRepository(c *gin.Context, projectId ProjectId, repositoryId RepositoryId)

	// (GET /projects/{projectId}/statuses)
	ListStatuses(c *gin.Context, projectId ProjectId)

	// (POST /projects/{projectId}/statuses)
	CreateStatus(c *gin.Context, projectId ProjectId)

	// (PATCH /projects/{projectId}/statuses/{statusId})
	UpdateStatus(c *gin.Context, projectId ProjectId, statusId StatusId)

	// (GET /projects/{projectId}/tasks)
	ListTasks(c *gin.Context, projectId ProjectId, params ListTasksParams)

	// (POST /projects/{projectId}/tasks)
	CreateTask(c *gin.Context, projectId ProjectId)

	// (PATCH /projects/{projectId}/tasks/{taskId})
	UpdateTask(c *gin.Context, projectId ProjectId, taskId TaskId)

	// (POST /public-pages/{pageId}/revoke)
	RevokePublicPage(c *gin.Context, pageId PageId)

	// (GET /public-pages/{pageId}/viewers)
	ListPublicPageViewers(c *gin.Context, pageId PageId)

	// (POST /public-pages/{pageId}/viewers)
	AddPublicPageViewer(c *gin.Context, pageId PageId)

	// (DELETE /public-pages/{pageId}/viewers/{userId})
	RemovePublicPageViewer(c *gin.Context, pageId PageId, userId UserId)

	// (GET /public/pages/{slug})
	GetPublicPage(c *gin.Context, slug PageSlug, params GetPublicPageParams)

	// (GET /readyz)
	Readiness(c *gin.Context)

	// (GET /sync/conflicts)
	ListSyncConflicts(c *gin.Context, params ListSyncConflictsParams)

	// (POST /sync/conflicts/{conflictId}/resolve)
	ResolveSyncConflict(c *gin.Context, conflictId ConflictId)

	// (GET /sync/runs)
	ListSyncRuns(c *gin.Context, params ListSyncRunsParams)

	// (GET /tenant)
	GetTenant(c *gin.Context)

	// (GET /tenant/invitations)
	ListInvitations(c *gin.Context)

	// (POST /tenant/invitations)
	CreateInvitation(c *gin.Context)

	// (POST /tenant/invitations/{token}/accept)
	AcceptInvitation(c *gin.Context, token InvitationToken)

	// (GET /tenant/members)
	ListTenantMembers(c *gin.Context)

	// (PATCH /tenant/members/{userId})
	UpdateTenantMember(c *gin.Context, userId UserId)

	// (GET /tenant/permissions)
	ListPermissionGrants(c *gin.Context, params ListPermissionGrantsParams)

	// (POST /tenant/permissions)
	CreatePermissionGrant(c *gin.Context)

	// (DELETE /tenant/permissions/{grantId})
	DeletePermissionGrant(c *gin.Context, grantId GrantId)

	// (POST /webhooks/github)
	ReceiveGitHubWebhook(c *gin.Context, params ReceiveGitHubWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAuditEvents(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAuditEvents(c, params)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// CompleteOIDC operation middleware
func (siw *ServerInterfaceWrapper) CompleteOIDC(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteOIDCParams

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteOIDC(c, params)
}

// StartOIDC operation middleware
func (siw *ServerInterfaceWrapper) StartOIDC(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartOIDC(c)
}

// LoginCustomer operation middleware
func (siw *ServerInterfaceWrapper) LoginCustomer(c *gin.Context) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug PageSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginCustomer(c, slug)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// CompleteGitHubAppInstall operation middleware
func (siw *ServerInterfaceWrapper) CompleteGitHubAppInstall(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteGitHubAppInstallParams

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "installation_id" -------------

	if paramValue := c.Query("installation_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument installation_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "installation_id", c.Request.URL.Query(), &params.InstallationId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter installation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteGitHubAppInstall(c, params)
}

// StartGitHubAppInstall operation middleware
func (siw *ServerInterfaceWrapper) StartGitHubAppInstall(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGitHubAppInstall(c)
}

// ListGitHubConnections operation middleware
func (siw *ServerInterfaceWrapper) ListGitHubConnections(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGitHubConnections(c)
}

// CompleteGitHubOAuth operation middleware
func (siw *ServerInterfaceWrapper) CompleteGitHubOAuth(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteGitHubOAuthParams

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteGitHubOAuth(c, params)
}

// StartGitHubOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartGitHubOAuth(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartGitHubOAuth(c)
}

// ListGitHubRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListGitHubRepositories(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGitHubRepositories(c)
}

// ListGitHubUserMappings operation middleware
func (siw *ServerInterfaceWrapper) ListGitHubUserMappings(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGitHubUserMappings(c)
}

// CreateGitHubUserMapping operation middleware
func (siw *ServerInterfaceWrapper) CreateGitHubUserMapping(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGitHubUserMapping(c)
}

// DeleteGitHubUserMapping operation middleware
func (siw *ServerInterfaceWrapper) DeleteGitHubUserMapping(c *gin.Context) {

	var err error

	// ------------- Path parameter "mappingId" -------------
	var mappingId MappingId

	err = runtime.BindStyledParameterWithOptions("simple", "mappingId", c.Param("mappingId"), &mappingId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter mappingId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGitHubUserMapping(c, mappingId)
}

// GetCurrentPrincipal operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentPrincipal(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentPrincipal(c)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProjects(c)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProject(c)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProject(c, projectId)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProject(c, projectId)
}

// ImportGitHubProject operation middleware
func (siw *ServerInterfaceWrapper) ImportGitHubProject(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportGitHubProject(c, projectId)
}

// ListLabels operation middleware
func (siw *ServerInterfaceWrapper) ListLabels(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLabels(c, projectId)
}

// CreateLabel operation middleware
func (siw *ServerInterfaceWrapper) CreateLabel(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLabel(c, projectId)
}

// ListMilestones operation middleware
func (siw *ServerInterfaceWrapper) ListMilestones(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMilestones(c, projectId)
}

// CreateMilestone operation middleware
func (siw *ServerInterfaceWrapper) CreateMilestone(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMilestone(c, projectId)
}

// UpdateMilestone operation middleware
func (siw *ServerInterfaceWrapper) UpdateMilestone(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "milestoneId" -------------
	var milestoneId MilestoneId

	err = runtime.BindStyledParameterWithOptions("simple", "milestoneId", c.Param("milestoneId"), &milestoneId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter milestoneId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMilestone(c, projectId, milestoneId)
}

// ListPublicPages operation middleware
func (siw *ServerInterfaceWrapper) ListPublicPages(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicPages(c, projectId)
}

// CreatePublicPage operation middleware
func (siw *ServerInterfaceWrapper) CreatePublicPage(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePublicPage(c, projectId)
}

// ListProjectRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListProjectRepositories(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProjectRepositories(c, projectId)
}

// AttachProjectRepository operation middleware
func (siw *ServerInterfaceWrapper) AttachProjectRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AttachProjectRepository(c, projectId)
}

// DetachProjectRepository operation middleware
func (siw *ServerInterfaceWrapper) DetachProjectRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repositoryId" -------------
	var repositoryId RepositoryId

	err = runtime.BindStyledParameterWithOptions("simple", "repositoryId", c.Param("repositoryId"), &repositoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repositoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DetachProjectRepository(c, projectId, repositoryId)
}

// ListStatuses operation middleware
func (siw *ServerInterfaceWrapper) ListStatuses(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListStatuses(c, projectId)
}

// CreateStatus operation middleware
func (siw *ServerInterfaceWrapper) CreateStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStatus(c, projectId)
}

// UpdateStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "statusId" -------------
	var statusId StatusId

	err = runtime.BindStyledParameterWithOptions("simple", "statusId", c.Param("statusId"), &statusId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statusId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStatus(c, projectId, statusId)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "statusId" -------------

	err = runtime.BindQueryParameter("form", true, false, "statusId", c.Request.URL.Query(), &params.StatusId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statusId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "milestoneId" -------------

	err = runtime.BindQueryParameter("form", true, false, "milestoneId", c.Request.URL.Query(), &params.MilestoneId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter milestoneId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTasks(c, projectId, params)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTask(c, projectId)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", c.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter taskId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTask(c, projectId, taskId)
}

// RevokePublicPage operation middleware
func (siw *ServerInterfaceWrapper) RevokePublicPage(c *gin.Context) {

	var err error

	// ------------- Path parameter "pageId" -------------
	var pageId PageId

	err = runtime.BindStyledParameterWithOptions("simple", "pageId", c.Param("pageId"), &pageId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokePublicPage(c, pageId)
}

// ListPublicPageViewers operation middleware
func (siw *ServerInterfaceWrapper) ListPublicPageViewers(c *gin.Context) {

	var err error

	// ------------- Path parameter "pageId" -------------
	var pageId PageId

	err = runtime.BindStyledParameterWithOptions("simple", "pageId", c.Param("pageId"), &pageId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicPageViewers(c, pageId)
}

// AddPublicPageViewer operation middleware
func (siw *ServerInterfaceWrapper) AddPublicPageViewer(c *gin.Context) {

	var err error

	// ------------- Path parameter "pageId" -------------
	var pageId PageId

	err = runtime.BindStyledParameterWithOptions("simple", "pageId", c.Param("pageId"), &pageId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddPublicPageViewer(c, pageId)
}

// RemovePublicPageViewer operation middleware
func (siw *ServerInterfaceWrapper) RemovePublicPageViewer(c *gin.Context) {

	var err error

	// ------------- Path parameter "pageId" -------------
	var pageId PageId

	err = runtime.BindStyledParameterWithOptions("simple", "pageId", c.Param("pageId"), &pageId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemovePublicPageViewer(c, pageId, userId)
}

// GetPublicPage operation middleware
func (siw *ServerInterfaceWrapper) GetPublicPage(c *gin.Context) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug PageSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicPageParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameter("form", true, false, "token", c.Request.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicPage(c, slug, params)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readiness(c)
}

// ListSyncConflicts operation middleware
func (siw *ServerInterfaceWrapper) ListSyncConflicts(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSyncConflictsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "projectId" -------------

	err = runtime.BindQueryParameter("form", true, false, "projectId", c.Request.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSyncConflicts(c, params)
}

// ResolveSyncConflict operation middleware
func (siw *ServerInterfaceWrapper) ResolveSyncConflict(c *gin.Context) {

	var err error

	// ------------- Path parameter "conflictId" -------------
	var conflictId ConflictId

	err = runtime.BindStyledParameterWithOptions("simple", "conflictId", c.Param("conflictId"), &conflictId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter conflictId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolveSyncConflict(c, conflictId)
}

// ListSyncRuns operation middleware
func (siw *ServerInterfaceWrapper) ListSyncRuns(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSyncRunsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSyncRuns(c, params)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTenant(c)
}

// ListInvitations operation middleware
func (siw *ServerInterfaceWrapper) ListInvitations(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInvitations(c)
}

// CreateInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateInvitation(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvitation(c)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(c *gin.Context) {

	var err error

	// ------------- Path parameter "token" -------------
	var token InvitationToken

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptInvitation(c, token)
}

// ListTenantMembers operation middleware
func (siw *ServerInterfaceWrapper) ListTenantMembers(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTenantMembers(c)
}

// UpdateTenantMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateTenantMember(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTenantMember(c, userId)
}

// ListPermissionGrants operation middleware
func (siw *ServerInterfaceWrapper) ListPermissionGrants(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPermissionGrantsParams

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameter("form", true, false, "userId", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "projectId" -------------

	err = runtime.BindQueryParameter("form", true, false, "projectId", c.Request.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPermissionGrants(c, params)
}

// CreatePermissionGrant operation middleware
func (siw *ServerInterfaceWrapper) CreatePermissionGrant(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePermissionGrant(c)
}

// DeletePermissionGrant operation middleware
func (siw *ServerInterfaceWrapper) DeletePermissionGrant(c *gin.Context) {

	var err error

	// ------------- Path parameter "grantId" -------------
	var grantId GrantId

	err = runtime.BindStyledParameterWithOptions("simple", "grantId", c.Param("grantId"), &grantId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter grantId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePermissionGrant(c, grantId)
}

// ReceiveGitHubWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveGitHubWebhook(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveGitHubWebhookParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Hub-Signature-256" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Hub-Signature-256")]; found {
		var XHubSignature256 string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Hub-Signature-256, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Hub-Signature-256", valueList[0], &XHubSignature256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Hub-Signature-256: %w", err), http.StatusBadRequest)
			return
		}

		params.XHubSignature256 = XHubSignature256

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Hub-Signature-256 is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-GitHub-Delivery" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Delivery")]; found {
		var XGitHubDelivery string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-GitHub-Delivery, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Delivery", valueList[0], &XGitHubDelivery, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-GitHub-Delivery: %w", err), http.StatusBadRequest)
			return
		}

		params.XGitHubDelivery = XGitHubDelivery

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-GitHub-Delivery is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-GitHub-Event" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Event")]; found {
		var XGitHubEvent string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-GitHub-Event, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Event", valueList[0], &XGitHubEvent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-GitHub-Event: %w", err), http.StatusBadRequest)
			return
		}

		params.XGitHubEvent = XGitHubEvent

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-GitHub-Event is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReceiveGitHubWebhook(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/audit/events", wrapper.ListAuditEvents)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/oidc/callback", wrapper.CompleteOIDC)
	router.GET(options.BaseURL+"/auth/oidc/start", wrapper.StartOIDC)
	router.POST(options.BaseURL+"/auth/public/pages/:slug/login", wrapper.LoginCustomer)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/auth/session", wrapper.GetSession)
	router.GET(options.BaseURL+"/healthz", wrapper.Health)
	router.GET(options.BaseURL+"/integrations/github/app/callback", wrapper.CompleteGitHubAppInstall)
	router.GET(options.BaseURL+"/integrations/github/app/install", wrapper.StartGitHubAppInstall)
	router.GET(options.BaseURL+"/integrations/github/connections", wrapper.ListGitHubConnections)
	router.GET(options.BaseURL+"/integrations/github/oauth/callback", wrapper.CompleteGitHubOAuth)
	router.GET(options.BaseURL+"/integrations/github/oauth/start", wrapper.StartGitHubOAuth)
	router.GET(options.BaseURL+"/integrations/github/repositories", wrapper.ListGitHubRepositories)
	router.GET(options.BaseURL+"/integrations/github/user-mappings", wrapper.ListGitHubUserMappings)
	router.POST(options.BaseURL+"/integrations/github/user-mappings", wrapper.CreateGitHubUserMapping)
	router.DELETE(options.BaseURL+"/integrations/github/user-mappings/:mappingId", wrapper.DeleteGitHubUserMapping)
	router.GET(options.BaseURL+"/me", wrapper.GetCurrentPrincipal)
	router.GET(options.BaseURL+"/projects", wrapper.ListProjects)
	router.POST(options.BaseURL+"/projects", wrapper.CreateProject)
	router.GET(options.BaseURL+"/projects/:projectId", wrapper.GetProject)
	router.PATCH(options.BaseURL+"/projects/:projectId", wrapper.UpdateProject)
	router.POST(options.BaseURL+"/projects/:projectId/github/import", wrapper.ImportGitHubProject)
	router.GET(options.BaseURL+"/projects/:projectId/labels", wrapper.ListLabels)
	router.POST(options.BaseURL+"/projects/:projectId/labels", wrapper.CreateLabel)
	router.GET(options.BaseURL+"/projects/:projectId/milestones", wrapper.ListMilestones)
	router.POST(options.BaseURL+"/projects/:projectId/milestones", wrapper.CreateMilestone)
	router.PATCH(options.BaseURL+"/projects/:projectId/milestones/:milestoneId", wrapper.UpdateMilestone)
	router.GET(options.BaseURL+"/projects/:projectId/public-pages", wrapper.ListPublicPages)
	router.POST(options.BaseURL+"/projects/:projectId/public-pages", wrapper.CreatePublicPage)
	router.GET(options.BaseURL+"/projects/:projectId/repositories", wrapper.ListProjectRepositories)
	router.POST(options.BaseURL+"/projects/:projectId/repositories", wrapper.AttachProjectRepository)
	router.DELETE(options.BaseURL+"/projects/:projectId/repositories/:repositoryId", wrapper.DetachProjectRepository)
	router.GET(options.BaseURL+"/projects/:projectId/statuses", wrapper.ListStatuses)
	router.POST(options.BaseURL+"/projects/:projectId/statuses", wrapper.CreateStatus)
	router.PATCH(options.BaseURL+"/projects/:projectId/statuses/:statusId", wrapper.UpdateStatus)
	router.GET(options.BaseURL+"/projects/:projectId/tasks", wrapper.ListTasks)
	router.POST(options.BaseURL+"/projects/:projectId/tasks", wrapper.CreateTask)
	router.PATCH(options.BaseURL+"/projects/:projectId/tasks/:taskId", wrapper.UpdateTask)
	router.POST(options.BaseURL+"/public-pages/:pageId/revoke", wrapper.RevokePublicPage)
	router.GET(options.BaseURL+"/public-pages/:pageId/viewers", wrapper.ListPublicPageViewers)
	router.POST(options.BaseURL+"/public-pages/:pageId/viewers", wrapper.AddPublicPageViewer)
	router.DELETE(options.BaseURL+"/public-pages/:pageId/viewers/:userId", wrapper.RemovePublicPageViewer)
	router.GET(options.BaseURL+"/public/pages/:slug", wrapper.GetPublicPage)
	router.GET(options.BaseURL+"/readyz", wrapper.Readiness)
	router.GET(options.BaseURL+"/sync/conflicts", wrapper.ListSyncConflicts)
	router.POST(options.BaseURL+"/sync/conflicts/:conflictId/resolve", wrapper.ResolveSyncConflict)
	router.GET(options.BaseURL+"/sync/runs", wrapper.ListSyncRuns)
	router.GET(options.BaseURL+"/tenant", wrapper.GetTenant)
	router.GET(options.BaseURL+"/tenant/invitations", wrapper.ListInvitations)
	router.POST(options.BaseURL+"/tenant/invitations", wrapper.CreateInvitation)
	router.POST(options.BaseURL+"/tenant/invitations/:token/accept", wrapper.AcceptInvitation)
	router.GET(options.BaseURL+"/tenant/members", wrapper.ListTenantMembers)
	router.PATCH(options.BaseURL+"/tenant/members/:userId", wrapper.UpdateTenantMember)
	router.GET(options.BaseURL+"/tenant/permissions", wrapper.ListPermissionGrants)
	router.POST(options.BaseURL+"/tenant/permissions", wrapper.CreatePermissionGrant)
	router.DELETE(options.BaseURL+"/tenant/permissions/:grantId", wrapper.DeletePermissionGrant)
	router.POST(options.BaseURL+"/webhooks/github", wrapper.ReceiveGitHubWebhook)
}
